### ISSUE TITLE
Where is the obfocusted ID?

### ISSUE THREAD

**Issue by duongtdvn** [Propaganistas/Laravel-FakeId#14]
So, I have installed the package correctly, and it seem to work but I did not see the obfocusted id anywhere in the collection. Bellow is what i am doing:

```php
Route::fakeIdModel('activity', 'App\Entities\Activity');
Route::get('activities', function ()
{
    $activities = \App\Entities\Activity::all();

    return $activities;
});

```

The collection is returned normally as the id still unobfocusted, so the only way to know it's fake id is calling `$model->getRouteKey()`.

**Comment by Propaganistas** [comment]
Hi there

FakeIds only get exposed in URLs when using Laravel's own methods. Let's say `8642` is the obfuscated ID for ID `1` and you have these routes in place:
```php
Route::fakeIdModel('activity', 'App\Entities\Activity');
Route::get('activities/{activity}', function($activity) {
   return $activity;
})->name('activity');
```
Then the following will happen:
* Calling `example.org/activities/1` will return `ModelNotFound`
* Calling `example.org/activities/8642` will return the activity with ID 1
* `route('activity', ['activity' => Activity::find(1)])` will render as `example.org/activities/8642`

The fake ID is more like a dynamic obfuscation. There's really no need to use the obfuscated ID anywhere directly, as you still need the "real" ID for working with the database.

If you do need to get hold of the obfuscated ID, then you can indeed use the `getRouteKey()` method. Or to extend your example:

```php
class Activity extends Model {

    protected $appends = ['fake_id'];

    public function getFakeIdAttribute() {
        return $this->getRouteKey();
    }

}
````
This will always include the fake ID as an model attribute.

**Comment by duongtdvn** [comment]
WoW, such a fastest response ever!

Yeah I got your point, but imagine if you list all `activities` to an index view, and you want a link to each individual `activity` then you will need to have the obfocusted id because the `real id` will lead to `ModelNotFound`. That why i need to know what is the obfocusted id. And one more reason which make me ask this question is because in the docs you wrote:

> All routes generated for this model will now automatically contain obfuscated IDs...

which make me think that the obfocusted id will be appended to the collection automatically.

**Comment by Propaganistas** [comment]
If you use Laravel's URL helpers then you don't need to know the obfuscated ID. It will be automatically constructed for you. Just pass the model object to the helper:

```
@foreach (Activity::all() as $activity)
    <a href="{{ route('activity', ['activity' => $activity]) }}"> REAL ID: {{ $activity->id }} </a>
@endforeach

```

Results in:
```
<a href="http://example.org/activity/8642"> REAL ID: 1 </a>
<a href="http://example.org/activity/2194"> REAL ID: 2 </a>
...
```

**Comment by duongtdvn** [comment]
Oops, I did not know that method is available out there, thank you so much!

**Comment by meNESS** [comment]
@duongtdvn @Propaganistas What about writing APIs? I return JSON as the response, and the response has non-obfuscated IDs, this would break the aim of obfuscating IDs.

**Comment by Propaganistas** [comment]
We can't make the ID obfuscate automatically when passing a model to a JSON function as overriding the `jsonSerialize()` (or `toArray()`) method is NOT viable. Leaving out or altering the model key within the JSON representation will break LOTS of things (e.g. serializing models into the database, ...).

If you really need to obfuscate the ID in API requests (which is rather uncommon by the way), your best shot is to implement a custom method and call that when you need a model in JSON:

```php
class MyModel extends Model {

    public function toApi() {
        return array_set(
            $this->toArray(),
            $this->getKeyName(),
            $this->getRouteKey()
        );
    }

}
```

**Comment by meNESS** [comment]
@Propaganistas Thanks for the information. I think it would break things too. I'm using transformers, I can encode IDs inside transformers.

> If you really need to obfuscate the ID in API requests (which is rather uncommon by the way)

What do you mean by saying that's uncommon? I'm using Laravel for making an API application. It receives obfuscated IDs and decodes them for internal use (thanks to your package). It also returns JSON as results. Clients should not access to decoded IDs! right?

**Comment by Propaganistas** [comment]
Yes, that's right. I actually meant one step further: if not required, you should probably even leave out the id / obfuscated id from the response.

**Comment by sebastiaanluca** [comment]
@Propaganistas

Hi, I have a somewhat related follow-up question on this.

Say you've got a resource that's using obfuscated IDs, e.g. `users`, and a second resource `posts` for which a user can be the author. If you only have access to obfuscated IDs on the client-side and want to create a post that requires a `user_id`, in the flow of things, where would you decode that ID so you can use it in validation rules and so on (i.e. checking the database with an `exists` rule to make sure it's a valid user)?

In a previous project, I've written middleware that checks the incoming request's input and decodes all `*_id` fields, but it's hardly ever the case all those IDs need to be decoded or that they follow that same format. Or do you just use the real ID and keep the obfuscation for routes only?

**Comment by Propaganistas** [comment]
@sebastiaanluca Decoding input automatically will give you a hard time since there's quite some indetermined stuff to take care of. For instance, input fields can be named completely custom, not all IDs should be decoded, ...

I personally tend to never expose column names (especially those holding keys). This requires you to be quite explicit about taking care of the request input and hence you can specify which input data to decode. For example, you could do something along these lines:
```php
use Illuminate\Facades\App;
use Illuminate\Facades\Request;
use Illuminate\Support\Arr;

trait DecodesIds {
    protected function decodeIds($fields)
    {
        $fields = is_array($fields) ? $fields : func_get_args();

        $input = Request::all();

        foreach ($fields as $field) {
            if (Arr::has($input, $field)) {
                $input[$field] = App::make('fakeid')->decode($input[$field]);
            }
        }

        Request::replace($input);
    }
}
```
```php
class PostsController extends Controller {

    use DecodesIds;

    public function __construct()
    {
        $this->decodeIds('user_id', 'post_id');
    }
}
```
By decoding in the Controller's constructor method I'm making sure that the remainder of the application (Controller, FormRequests, Validation, ...) receives decoded input. You could compare this with an explicit version of your middleware.

If you do prefer to have some automatic decoding going on and will always use the *magical wired nature of Eloquent's relationships*, you could add some configuration to the application containing all models using the FakeId trait and then extend your middleware to check if there are request fields named after any of the configured models' relations... However I'm certainly not vouching for this.

I hope this answers your question?

**Comment by sebastiaanluca** [comment]
Thank you for your extended reply! Highly appreciated.

Your example of decoding IDs is somewhat similar to what I had, but the thought of doing so in the controller constructor hadn't even occurred to me. This does allow setting the input fields to be decoded per resource, which is more in lines of what I was looking for.

Decoding IDs in middleware is indeed a PITA, especially since input fields are arbitrary and don't always end with `_id`. Checking Eloquent models that are using fake IDs and their relations is also a possible flow, but as you've insinuated, highly discouraged because of its *magic* :D

I'm starting a new project this week for which I'm going to implement fake IDs from the start. I'll see what gives and how to perhaps optimize it by introducing some automatic resolving/decoding if at all possible.

You also say

> I personally tend to never expose column names (especially those holding keys).

Can you elaborate on that? Do you manually remap column names before outputting them to JSON (if you're building an API) or a form (if, say, you're building a CRUD view)? What's the reason for doing so?

Thanks again!

**Comment by Propaganistas** [comment]
Let's continue this discussion elsewhere.
