### ISSUE TITLE
Hashid not showing in route() function

### ISSUE THREAD

**Issue by KickSchutte67** [Propaganistas/Laravel-FakeId#47]
Hi! 

I have the following issue;

When creating a new model instance I get redirected to the hash ID. This is all working correctly.

But when using the route() helper inside my component I keep getting the primary key instead of the random hash ID.
![Screenshot 2022-12-16 at 11 27 31](https://user-images.githubusercontent.com/31417270/208078425-b1a34cc6-6799-4838-bce2-01c1251fd984.png)

I am using Inertia.js with Vue.js.

`Index.vue`
<img width="614" alt="Screenshot 2022-12-16 at 11 21 13" src="https://user-images.githubusercontent.com/31417270/208077290-320385b7-ef1d-423d-9c6a-5c90ed35accf.png">

`Address instance`
![Screenshot 2022-12-16 at 11 24 36](https://user-images.githubusercontent.com/31417270/208077920-5effabbc-0e9a-42ec-a043-3e02b78486a2.png)

`web.php`
<img width="723" alt="Screenshot 2022-12-16 at 11 22 02" src="https://user-images.githubusercontent.com/31417270/208077422-f84c4f16-88fa-4c6c-baf7-a628ed6ab274.png">

`RouteServceProvider`
<img width="721" alt="Screenshot 2022-12-16 at 11 22 52" src="https://user-images.githubusercontent.com/31417270/208077552-8d4e3bb4-f1cd-4b29-9207-ab3bef0a752a.png">

`Address.php`
<img width="463" alt="Screenshot 2022-12-16 at 11 23 12" src="https://user-images.githubusercontent.com/31417270/208077640-482508c2-f198-4771-bef2-0afd551d0e0c.png">

What am I doing wrong?

**Comment by Propaganistas** [comment]
Although named equally, the `route` function you're using in your Vue files is... well... javascript.
The package makes use of Eloquent Model functionality and therefore can only hook into server-side behavior, being PHP and consequentially also Blade. 

You could make the model being exposed to Vue to output the hash ID (`$model->getRouteKey()`) instead of the original ID (`$model->getKey()`). There are various ways to do this... In-place mapping, API resources, making use of `$hidden` and `$appends` in the Model class, ...
