### ISSUE TITLE
When running the setup I get the error “Undefined function gmp_intval()”

### ISSUE THREAD

**Issue by seblavoie** [Propaganistas/Laravel-FakeId#5]
Hi, I tried installing the package and, when running `php artisan fakeid:setup`, I get this error: 

```
Symfony\Component\Debug\Exception\FatalThrowableError]                       
Call to undefined function Propaganistas\LaravelFakeId\Commands\gmp_intval() 
```

The stack trace points it to line 33. 

I don't know much about `gmp_intval()`. Do I need to install something to make this work? I am running it from the homestead vm.

**Comment by Propaganistas** [comment]
The `gmp_intval()` function (which requires GMP) was introduced because the `BigInteger` class (which is used by Optimus) showed some memory instabilities. These issues are now resolved. At the moment I'm waiting for my Optimus PR to be accepted so this piece of code can be replaced again.

In the meantime, if your system does not support GMP, please perform the following steps in order to manually setup fakeid:

In the root of the Laravel app, run `./vendor/bin/optimus spark` in the command line and make a note of the generated numbers, e.g.:

> Prime: 1213751501
> Inverse: 1320061957
> Random: 1324142685

Use these numbers to create the following entries in your `.env` file:
```
FAKEID_PRIME=1213751501
FAKEID_INVERSE=1320061957
FAKEID_RANDOM=1324142685
 ```

That's it.

**Comment by seblavoie** [comment]
Okay great, that seems to all be working well. Thanks for the support! 👍

**Comment by Propaganistas** [comment]
FYI, the PR I mentioned has been accepted in the meantime. Now you can safely use `php artisan fakeid:setup` in any use case.
