### ISSUE TITLE
Seems not to work with route caching

### ISSUE THREAD

**Issue by hughgrigg** [Propaganistas/Laravel-FakeId#6]
As far as I can tell, this package currently does not work with Laravel's route caching. If route caching is enabled, all fake id routes result in a 404. They all work with caching disabled.

I'm going to investigate and hopefully submit a PR, just putting in this issue in case this is already a known or solveable issue.

**Comment by Propaganistas** [comment]
Route caching doesn't work for route definitions (including `Route::bind()`, `Route::model()` and `Route::fakeIdModel()`) based on Closures. As `Route::fakeIdModel()` is merely a wrapper for a custom defined `Route::bind(Closure)` definition, caching won't be able to incorporate these routes.

If we could find a way to omit the use of a Closure when defining the `fakeIdModel()`-wrapper, it should work theoretically.

**Comment by Propaganistas** [comment]
Due to the nature of Laravel's route caching (base_64 encoding of the routes file), route bindings get stripped. If you want to make use of route caching, please move the Fake Id bindings (`Route::fakeIdModel()`) to the `boot` method of `RouteServiceProvider`. This way they won't get stripped and everything should work as expected.

**Comment by hughgrigg** [comment]
Excellent, thanks for the tip.
